### ISSUE TITLE
Push new version to rubygems

### ISSUE THREAD

**Issue by krsyoung** [cloudfoundry/omniauth-uaa-oauth2#10]
Hey folks, would it be possible to push an update version of this Gem to rubygems?  The last version pushed was from February 7, 2014 and there has been a lot of good activity in the commits since then.

Thanks!

**Comment by sreetummidi** [comment]
Closing this as we don't have plans to push newer versions of the gem at this time

**Comment by dcarley** [comment]
> Closing this as we don't have plans to push newer versions of the gem at this time

Can you describe why?
